/* ============================================================
 * 法考电子法条（本地版） v1
 * 数据完全来自内置 law-data.js（由众合 listV2/infoV2 接口汇总）
 * ============================================================ */
(() => {
  "use strict";
  const $app=document.getElementById("app"),$list=document.getElementById("list"),$right=document.getElementById("right"),$empty=document.getElementById("empty"),$crumb=document.getElementById("crumb"),$btnBack=document.getElementById("btn-nav-back"),$input=document.getElementById("search-input"),$btnSrch=document.getElementById("btn-search"),$btnPrev=document.getElementById("btn-prev"),$btnNext=document.getElementById("btn-next"),$btnMax=document.getElementById("btn-max"),$resizer=document.getElementById("resizer");
  if(typeof window.LAW_DATA==="undefined"){$list.innerHTML=`<div style="padding:16px;color:var(--text-3)">未找到 law-data.js。请确认同目录下存在该文件。</div>`;return;}
  const DATA=window.LAW_DATA;
  const byId=new Map();
  function indexTree(nodes,parentTitle){const stack=[{nodes,parentTitle:""}];while(stack.length){const{nodes,parentTitle:pt}=stack.pop();for(const n of nodes){n._crumbs=pt?`${pt} / ${n.title}`:n.title;byId.set(n.id,n);if(n.children&&n.children.length){stack.push({nodes:n.children,parentTitle:n._crumbs});}}}}
  indexTree(DATA.tree,"");
  const state={openIds:new Set(),activeId:null,hits:[],hitIndex:-1,isSearching:false,history:[]};
  if(DATA.tree.length){state.openIds.add(DATA.tree[0].id);}
  function renderTree(){$list.innerHTML="";const frag=document.createDocumentFragment();DATA.tree.forEach(n=>frag.appendChild(buildNode(n,0)));$list.appendChild(frag);}
  function buildNode(node,depth){const hasChildren=!!(node.children&&node.children.length);const wrap=document.createElement("div");wrap.className="node";wrap.dataset.id=node.id;wrap.dataset.type=node.type;if(state.openIds.has(node.id))wrap.classList.add("is-open");if(state.activeId===node.id)wrap.classList.add("is-active");if(state.isSearching&&state.hits.includes(node.id))wrap.classList.add("is-hit");if(state.isSearching&&state.hits[state.hitIndex]===node.id)wrap.classList.add("is-hit-current");const row=document.createElement("div");row.className="node__row";row.style.paddingLeft=`${8+depth*14}px`;const toggle=document.createElement("span");toggle.className="node__toggle";if(!hasChildren)toggle.classList.add("is-empty");toggle.textContent="›";row.appendChild(toggle);const icon=document.createElement("span");icon.className="node__icon";icon.innerHTML=iconSvg(node.type);row.appendChild(icon);const title=document.createElement("span");title.className="node__title";title.textContent=node.title;row.appendChild(title);const tag=document.createElement("span");tag.className="node__type";tag.textContent=typeLabel(node.type);row.appendChild(tag);wrap.appendChild(row);if(hasChildren){const childBox=document.createElement("div");childBox.className="node__children";node.children.forEach(c=>childBox.appendChild(buildNode(c,depth+1)));wrap.appendChild(childBox);}row.addEventListener("click",(e)=>{e.stopPropagation();handleClick(node,wrap);});toggle.addEventListener("click",(e)=>{e.stopPropagation();if(hasChildren){if(state.openIds.has(node.id))state.openIds.delete(node.id);else state.openIds.add(node.id);renderTree();}});return wrap;}
  function typeLabel(t){return({0:"学科",1:"法典",2:"编",3:"分编",4:"章"})[t]||"";}
  function iconSvg(t){if(t===0)return `<svg viewBox="0 0 16 16" width="14" height="14"><path d="M2 3h12v10H2zM2 6h12" fill="none" stroke="currentColor" stroke-width="1.2"/></svg>`;if(t===1)return `<svg viewBox="0 0 16 16" width="14" height="14"><path d="M3 2h7l3 3v9H3z M10 2v3h3" fill="none" stroke="currentColor" stroke-width="1.2"/></svg>`;if(t===2)return `<svg viewBox="0 0 16 16" width="14" height="14"><path d="M2 4h5l1.5 1.5H14V13H2z" fill="none" stroke="currentColor" stroke-width="1.2"/></svg>`;return `<svg viewBox="0 0 16 16" width="14" height="14"><circle cx="4" cy="8" r="1.2" fill="currentColor"/></svg>`;}
  function handleClick(node,wrap){const hasChildren=!!(node.children&&node.children.length);if(node.type===4){state.activeId=node.id;ensureParentsOpen(node.id);state.openIds.add(parentsById(node.id).filter(p=>>(p.children||[]).length).map(p=>p.id));pushHistory(node.id);renderTree();renderArticle(node);return;}if(node.type===2){if(!state.openIds.has(node.id))state.openIds.add(node.id);state.activeId=node.id;pushHistory(node.id);renderTree();renderBian(node);return;}if(node.type===3){if(!state.openIds.has(node.id))state.openIds.add(node.id);state.activeId=node.id;pushHistory(node.id);renderTree();renderBian(node);return;}if(state.openIds.has(node.id))state.openIds.delete(node.id);else state.openIds.add(node.id);renderTree();}
  function parentsById(id){const out=[];let n=byId.get(id);while(n){const p=byId.get(n.parentId);if(!p)break;out.push(p);n=p;}return out;}
  function ensureParentsOpen(id){const ps=parentsById(id);for(const p of ps)state.openIds.add(p.id);}
  function pushHistory(id){if(state.history.length&&state.history[state.history.length-1]===id)return;state.history.push(id);if(state.history.length>60)state.history.shift();}
  function goBack(){if(state.history.length<=1)return;state.history.pop();const id=state.history[state.history.length-1];const node=byId.get(id);state.activeId=id;ensureParentsOpen(id);renderTree();if(!node)return;if(node.type===2||node.type===3)renderBian(node);else renderArticle(node);}
  function renderArticle(node){const renderUnit=findRenderUnit(node);$crumb.textContent=(byId.get(node.id)?._crumbs)||"";if(!renderUnit){const content=(DATA.contents[node.id]&&DATA.contents[node.id][0]?.content)||"";$right.innerHTML="";if(!content){$right.appendChild(emptyHint(node));return;}const wrap=document.createElement("article");wrap.className="law-block";wrap.innerHTML=`<h2 class="law-block__title" id="right_${node.id}">${escapeHtml(node.title)}</h2>`;const body=document.createElement("div");body.className="law-block__body";body.innerHTML=formatContent(content);wrap.appendChild(body);$right.appendChild(wrap);return;}renderBian(renderUnit);}
  function findRenderUnit(node){let cur=node;if(cur.type===2||cur.type===3)return cur;while(cur){const p=byId.get(cur.parentId);if(!p)break;if(p.type===3||p.type===2||p.type===1)return p;cur=p;}return null;}
  function renderBian(bianNode){$crumb.textContent=bianNode._crumbs||"";const chapters=DATA.contents[bianNode.id]||[];if(!chapters.length){$right.innerHTML="";const empty=document.createElement("div");empty.className="empty";empty.innerHTML=`<div class="empty__title">未抓取此编的条文</div><div class="empty__hint">本编 “${escapeHtml(bianNode.title)}” 在内置数据中未找到正文。请确认 law-data.js 已抓取完整。</div>`;$right.appendChild(empty);return;}const frag=document.createDocumentFragment();chapters.forEach(ch=>{const block=document.createElement("article");block.className="law-block";const titleId=`right_${ch.id}`;block.innerHTML=`<h2 class="law-block__title" id="${titleId}">${escapeHtml(ch.title)}</h2>`;const body=document.createElement("div");body.className="law-block__body";body.innerHTML=formatContent(ch.content||"");block.appendChild(body);frag.appendChild(block);});const haveIds=new Set(chapters.map(c=>c.id));const missing=(bianNode.children||[]).filter(c=>c.type===4&&!haveIds.has(c.id));if(missing.length){const tBlock=document.createElement("article");tBlock.className="law-block";tBlock.innerHTML=`<h2 class="law-block__title">${escapeHtml(bianNode.title)} · 子章节索引</h2>`;const body=document.createElement("div");body.className="law-block__body";body.style.fontSize="14px";body.style.lineHeight="1.8";body.innerHTML=missing.map(m=>`<div class="p">· <b>${escapeHtml(m.title)}</b>（未抓取正文）</div>`).join("");tBlock.appendChild(body);frag.appendChild(tBlock);}$right.innerHTML="";$right.appendChild(frag);requestAnimationFrame(()=>{if(state.activeId){const t=document.getElementById(`right_${state.activeId}`);if(t){$right.scrollTo({top:t.offsetTop-12,behavior:"smooth"});t.style.background="color-mix(in oklab, var(--hit) 55%, transparent)";setTimeout(()=>{t.style.background="";},1200);}}else{$right.scrollTo({top:0});}});}
  function emptyHint(node){const div=document.createElement("div");div.className="empty";div.innerHTML=`<div class="empty__title">${escapeHtml(node.title)}</div><div class="empty__hint">该节点暂无正文数据。</div>`;return div;}
  function formatContent(text){if(!text)return "";const paragraphs=text.split(/\n+/);return paragraphs.map(p=>p.trim()).filter(Boolean).map(p=>{const m=p.match(/^(第[一二三四五六七八九十百千〇零0-9]{1,8}[条编章节款项目])\s*[、\.：:]?\s*(.*)$/);let html;if(m){const lead=m[1];const rest=m[2];html=`<span class="lead-tiao">${escapeHtml(lead)}</span> ${escapeHtml(rest)}`;}else{html=escapeHtml(p);}return `<p class="p">${html}</p>`;}).join("");}
  function escapeHtml(s){return String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}
  function runSearch(){const raw=$input.value.trim();state.isSearching=raw.length>0;if(!state.isSearching){state.hits=[];state.hitIndex=-1;renderTree();return;}const tokens=raw.split(/\s+/).filter(Boolean);state.hits=[];walk(DATA.tree,(n)=>{const t=n.title.replace(/\s*/g,"");if(tokens.every(tk=>t.indexOf(tk)!==-1)){state.hits.push(n.id);ensureParentsOpen(n.id);}});state.hitIndex=state.hits.length?0:-1;renderTree();if(state.hits.length)jumpToHit();}
  function walk(nodes,fn){const stack=[...nodes];while(stack.length){const n=stack.pop();fn(n);if(n.children)for(let i=n.children.length-1;i>=0;i--)stack.push(n.children[i]);}}
  function jumpToHit(){const id=state.hits[state.hitIndex];if(!id)return;const node=byId.get(id);if(!node)return;state.activeId=id;ensureParentsOpen(id);renderTree();if(node.type===2||node.type===3)renderBian(node);else renderArticle(node);requestAnimationFrame(()=>{const m=document.querySelector("mark.hl.is-current");if(m)m.scrollIntoView({behavior:"smooth",block:"center"});else{const t=document.getElementById(`right_${id}`);if(t)$right.scrollTo({top:t.offsetTop-12,behavior:"smooth"});}});}
  function moveHit(delta){if(!state.hits.length)return;state.hitIndex=(state.hitIndex+delta+state.hits.length)%state.hits.length;renderTree();jumpToHit();}
  (function bindResizer(){let dragging=false;$resizer.addEventListener("mousedown",(e)=>{dragging=true;document.body.style.cursor="col-resize";e.preventDefault();});window.addEventListener("mousemove",(e)=>{if(!dragging)return;const rect=$app.getBoundingClientRect();const x=e.clientX-rect.left;const w=Math.min(Math.max(220,x),rect.width-360);document.documentElement.style.setProperty("--left-w",`${w}px`);});window.addEventListener("mouseup",()=>{if(!dragging)return;dragging=false;document.body.style.cursor="";});})();
  $btnBack.addEventListener("click",goBack);$btnSrch.addEventListener("click",runSearch);$btnPrev.addEventListener("click",()=>moveHit(-1));$btnNext.addEventListener("click",()=>moveHit(1));$input.addEventListener("keydown",(e)=>{if(e.key==="Enter"){e.preventDefault();runSearch();}if(e.key==="Escape"){$input.value="";runSearch();}});$btnMax.addEventListener("click",()=>$app.classList.toggle("is-max"));
  window.addEventListener("keydown",(e)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$input.focus();$input.select();}if(e.key==="Escape"&&document.activeElement===$input){$input.value="";runSearch();}});
  renderTree();if(DATA.tree.length){$crumb.textContent="";}
  window.__LAW={state,runSearch,moveHit,byId};
})();